/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.validation;

import de.ragedev.cdsl.validation.AbstractCDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CDSLValidator extends AbstractCDSLValidator {
}
