/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.ui.contentassist;

import de.ragedev.cdsl.ui.contentassist.AbstractCDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CDSLProposalProvider extends AbstractCDSLProposalProvider {
}
