/*
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.ui.tests;

import com.google.inject.Injector;
import de.ragedev.cdsl.ui.internal.CdslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class CDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CdslActivator.getInstance().getInjector("de.ragedev.cdsl.CDSL");
	}

}
