/*
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CDSLRuntimeModule extends AbstractCDSLRuntimeModule {
}
