/*
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CDSLStandaloneSetup extends CDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new CDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
