/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL.tests;

import de.ragedev.cdsl.cDSL.CDSLFactory;
import de.ragedev.cdsl.cDSL.NotAllowedRef;
import junit.framework.TestCase;
import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Not Allowed Ref</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class NotAllowedRefTest extends TestCase {

	/**
	 * The fixture for this Not Allowed Ref test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotAllowedRef fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(NotAllowedRefTest.class);
	}

	/**
	 * Constructs a new Not Allowed Ref test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotAllowedRefTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Not Allowed Ref test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(NotAllowedRef fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Not Allowed Ref test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotAllowedRef getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CDSLFactory.eINSTANCE.createNotAllowedRef());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //NotAllowedRefTest
