/*
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCDSLScopeProvider extends DelegatingScopeProvider {
}
