/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl;

import de.ragedev.cdsl.CDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CDSLStandaloneSetup extends CDSLStandaloneSetupGenerated {
  public static void doSetup() {
    CDSLStandaloneSetup _cDSLStandaloneSetup = new CDSLStandaloneSetup();
    _cDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
