/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl;

import de.ragedev.cdsl.AbstractCDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CDSLRuntimeModule extends AbstractCDSLRuntimeModule {
}
