/**
 * generated by Xtext 2.9.1
 */
package de.raphaegeissler.cdsl.cDSL.tests;

import de.raphaegeissler.cdsl.cDSL.AbstractEntry;
import de.raphaegeissler.cdsl.cDSL.CDSLFactory;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Abstract Entry</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class AbstractEntryTest extends TestCase {

	/**
	 * The fixture for this Abstract Entry test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractEntry fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(AbstractEntryTest.class);
	}

	/**
	 * Constructs a new Abstract Entry test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AbstractEntryTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Abstract Entry test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(AbstractEntry fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Abstract Entry test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractEntry getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CDSLFactory.eINSTANCE.createAbstractEntry());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //AbstractEntryTest
