/**
 * generated by Xtext 2.9.1
 */
package de.raphaegeissler.cdsl.cDSL.tests;

import de.raphaegeissler.cdsl.cDSL.CDSLFactory;
import de.raphaegeissler.cdsl.cDSL.ComponentDescription;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Component Description</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ComponentDescriptionTest extends AbstractEntryTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ComponentDescriptionTest.class);
	}

	/**
	 * Constructs a new Component Description test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComponentDescriptionTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Component Description test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected ComponentDescription getFixture() {
		return (ComponentDescription)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CDSLFactory.eINSTANCE.createComponentDescription());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ComponentDescriptionTest
