/**
 * generated by Xtext 2.9.1
 */
package de.raphaegeissler.cdsl.cDSL.tests;

import de.raphaegeissler.cdsl.cDSL.CDSLFactory;
import de.raphaegeissler.cdsl.cDSL.DValidator;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>DValidator</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DValidatorTest extends AbstractEntryTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DValidatorTest.class);
	}

	/**
	 * Constructs a new DValidator test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DValidatorTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this DValidator test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected DValidator getFixture() {
		return (DValidator)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CDSLFactory.eINSTANCE.createDValidator());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DValidatorTest
