/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.ragedev.cdsl.cDSL.CDSLPackage#getAbstractEntry()
 * @model
 * @generated
 */
public interface AbstractEntry extends EObject
{
} // AbstractEntry
