/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.ragedev.cdsl.cDSL.CDSLFactory
 * @model kind="package"
 * @generated
 */
public interface CDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ragedev.de/cdsl/CDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CDSLPackage eINSTANCE = de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.DomainmodelImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ENTRIES = 0;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.AbstractEntryImpl <em>Abstract Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.AbstractEntryImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getAbstractEntry()
   * @generated
   */
  int ABSTRACT_ENTRY = 1;

  /**
   * The number of structural features of the '<em>Abstract Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ENTRY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.DValidatorImpl <em>DValidator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.DValidatorImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getDValidator()
   * @generated
   */
  int DVALIDATOR = 2;

  /**
   * The feature id for the '<em><b>Val Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DVALIDATOR__VAL_NAME = ABSTRACT_ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref Components</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DVALIDATOR__REF_COMPONENTS = ABSTRACT_ENTRY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>DValidator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DVALIDATOR_FEATURE_COUNT = ABSTRACT_ENTRY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.ComponentDescriptionImpl <em>Component Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.ComponentDescriptionImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getComponentDescription()
   * @generated
   */
  int COMPONENT_DESCRIPTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DESCRIPTION__NAME = ABSTRACT_ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ports</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DESCRIPTION__PORTS = ABSTRACT_ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Units</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DESCRIPTION__UNITS = ABSTRACT_ENTRY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Not Allowed Ref</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DESCRIPTION__NOT_ALLOWED_REF = ABSTRACT_ENTRY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Component Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DESCRIPTION_FEATURE_COUNT = ABSTRACT_ENTRY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.PortsImpl <em>Ports</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.PortsImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getPorts()
   * @generated
   */
  int PORTS = 4;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTS__PORT = 0;

  /**
   * The number of structural features of the '<em>Ports</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.NotAllowedRefImpl <em>Not Allowed Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.NotAllowedRefImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getNotAllowedRef()
   * @generated
   */
  int NOT_ALLOWED_REF = 5;

  /**
   * The feature id for the '<em><b>Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_ALLOWED_REF__UNITS = 0;

  /**
   * The number of structural features of the '<em>Not Allowed Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_ALLOWED_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.UnitElementsImpl <em>Unit Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.UnitElementsImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getUnitElements()
   * @generated
   */
  int UNIT_ELEMENTS = 6;

  /**
   * The feature id for the '<em><b>Unit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT_ELEMENTS__UNIT = 0;

  /**
   * The number of structural features of the '<em>Unit Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT_ELEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.ragedev.cdsl.cDSL.impl.ComponentIDImpl <em>Component ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ragedev.cdsl.cDSL.impl.ComponentIDImpl
   * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getComponentID()
   * @generated
   */
  int COMPONENT_ID = 7;

  /**
   * The feature id for the '<em><b>Qualified Names</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ID__QUALIFIED_NAMES = 0;

  /**
   * The number of structural features of the '<em>Component ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ID_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see de.ragedev.cdsl.cDSL.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link de.ragedev.cdsl.cDSL.Domainmodel#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see de.ragedev.cdsl.cDSL.Domainmodel#getEntries()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Entries();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.AbstractEntry <em>Abstract Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Entry</em>'.
   * @see de.ragedev.cdsl.cDSL.AbstractEntry
   * @generated
   */
  EClass getAbstractEntry();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.DValidator <em>DValidator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DValidator</em>'.
   * @see de.ragedev.cdsl.cDSL.DValidator
   * @generated
   */
  EClass getDValidator();

  /**
   * Returns the meta object for the attribute '{@link de.ragedev.cdsl.cDSL.DValidator#getValName <em>Val Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val Name</em>'.
   * @see de.ragedev.cdsl.cDSL.DValidator#getValName()
   * @see #getDValidator()
   * @generated
   */
  EAttribute getDValidator_ValName();

  /**
   * Returns the meta object for the reference list '{@link de.ragedev.cdsl.cDSL.DValidator#getRefComponents <em>Ref Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ref Components</em>'.
   * @see de.ragedev.cdsl.cDSL.DValidator#getRefComponents()
   * @see #getDValidator()
   * @generated
   */
  EReference getDValidator_RefComponents();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.ComponentDescription <em>Component Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Description</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentDescription
   * @generated
   */
  EClass getComponentDescription();

  /**
   * Returns the meta object for the attribute '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentDescription#getName()
   * @see #getComponentDescription()
   * @generated
   */
  EAttribute getComponentDescription_Name();

  /**
   * Returns the meta object for the containment reference '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ports</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentDescription#getPorts()
   * @see #getComponentDescription()
   * @generated
   */
  EReference getComponentDescription_Ports();

  /**
   * Returns the meta object for the containment reference '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getUnits <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Units</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentDescription#getUnits()
   * @see #getComponentDescription()
   * @generated
   */
  EReference getComponentDescription_Units();

  /**
   * Returns the meta object for the containment reference list '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getNotAllowedRef <em>Not Allowed Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Not Allowed Ref</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentDescription#getNotAllowedRef()
   * @see #getComponentDescription()
   * @generated
   */
  EReference getComponentDescription_NotAllowedRef();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.Ports <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ports</em>'.
   * @see de.ragedev.cdsl.cDSL.Ports
   * @generated
   */
  EClass getPorts();

  /**
   * Returns the meta object for the attribute list '{@link de.ragedev.cdsl.cDSL.Ports#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Port</em>'.
   * @see de.ragedev.cdsl.cDSL.Ports#getPort()
   * @see #getPorts()
   * @generated
   */
  EAttribute getPorts_Port();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.NotAllowedRef <em>Not Allowed Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Allowed Ref</em>'.
   * @see de.ragedev.cdsl.cDSL.NotAllowedRef
   * @generated
   */
  EClass getNotAllowedRef();

  /**
   * Returns the meta object for the reference list '{@link de.ragedev.cdsl.cDSL.NotAllowedRef#getUnits <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Units</em>'.
   * @see de.ragedev.cdsl.cDSL.NotAllowedRef#getUnits()
   * @see #getNotAllowedRef()
   * @generated
   */
  EReference getNotAllowedRef_Units();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.UnitElements <em>Unit Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unit Elements</em>'.
   * @see de.ragedev.cdsl.cDSL.UnitElements
   * @generated
   */
  EClass getUnitElements();

  /**
   * Returns the meta object for the containment reference list '{@link de.ragedev.cdsl.cDSL.UnitElements#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Unit</em>'.
   * @see de.ragedev.cdsl.cDSL.UnitElements#getUnit()
   * @see #getUnitElements()
   * @generated
   */
  EReference getUnitElements_Unit();

  /**
   * Returns the meta object for class '{@link de.ragedev.cdsl.cDSL.ComponentID <em>Component ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component ID</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentID
   * @generated
   */
  EClass getComponentID();

  /**
   * Returns the meta object for the attribute list '{@link de.ragedev.cdsl.cDSL.ComponentID#getQualifiedNames <em>Qualified Names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Qualified Names</em>'.
   * @see de.ragedev.cdsl.cDSL.ComponentID#getQualifiedNames()
   * @see #getComponentID()
   * @generated
   */
  EAttribute getComponentID_QualifiedNames();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CDSLFactory getCDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.DomainmodelImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ENTRIES = eINSTANCE.getDomainmodel_Entries();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.AbstractEntryImpl <em>Abstract Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.AbstractEntryImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getAbstractEntry()
     * @generated
     */
    EClass ABSTRACT_ENTRY = eINSTANCE.getAbstractEntry();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.DValidatorImpl <em>DValidator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.DValidatorImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getDValidator()
     * @generated
     */
    EClass DVALIDATOR = eINSTANCE.getDValidator();

    /**
     * The meta object literal for the '<em><b>Val Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DVALIDATOR__VAL_NAME = eINSTANCE.getDValidator_ValName();

    /**
     * The meta object literal for the '<em><b>Ref Components</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DVALIDATOR__REF_COMPONENTS = eINSTANCE.getDValidator_RefComponents();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.ComponentDescriptionImpl <em>Component Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.ComponentDescriptionImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getComponentDescription()
     * @generated
     */
    EClass COMPONENT_DESCRIPTION = eINSTANCE.getComponentDescription();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_DESCRIPTION__NAME = eINSTANCE.getComponentDescription_Name();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DESCRIPTION__PORTS = eINSTANCE.getComponentDescription_Ports();

    /**
     * The meta object literal for the '<em><b>Units</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DESCRIPTION__UNITS = eINSTANCE.getComponentDescription_Units();

    /**
     * The meta object literal for the '<em><b>Not Allowed Ref</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DESCRIPTION__NOT_ALLOWED_REF = eINSTANCE.getComponentDescription_NotAllowedRef();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.PortsImpl <em>Ports</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.PortsImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getPorts()
     * @generated
     */
    EClass PORTS = eINSTANCE.getPorts();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORTS__PORT = eINSTANCE.getPorts_Port();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.NotAllowedRefImpl <em>Not Allowed Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.NotAllowedRefImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getNotAllowedRef()
     * @generated
     */
    EClass NOT_ALLOWED_REF = eINSTANCE.getNotAllowedRef();

    /**
     * The meta object literal for the '<em><b>Units</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_ALLOWED_REF__UNITS = eINSTANCE.getNotAllowedRef_Units();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.UnitElementsImpl <em>Unit Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.UnitElementsImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getUnitElements()
     * @generated
     */
    EClass UNIT_ELEMENTS = eINSTANCE.getUnitElements();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNIT_ELEMENTS__UNIT = eINSTANCE.getUnitElements_Unit();

    /**
     * The meta object literal for the '{@link de.ragedev.cdsl.cDSL.impl.ComponentIDImpl <em>Component ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ragedev.cdsl.cDSL.impl.ComponentIDImpl
     * @see de.ragedev.cdsl.cDSL.impl.CDSLPackageImpl#getComponentID()
     * @generated
     */
    EClass COMPONENT_ID = eINSTANCE.getComponentID();

    /**
     * The meta object literal for the '<em><b>Qualified Names</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_ID__QUALIFIED_NAMES = eINSTANCE.getComponentID_QualifiedNames();

  }

} //CDSLPackage
