/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.ragedev.cdsl.cDSL.CDSLPackage
 * @generated
 */
public interface CDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CDSLFactory eINSTANCE = de.ragedev.cdsl.cDSL.impl.CDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Domainmodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domainmodel</em>'.
   * @generated
   */
  Domainmodel createDomainmodel();

  /**
   * Returns a new object of class '<em>Abstract Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Entry</em>'.
   * @generated
   */
  AbstractEntry createAbstractEntry();

  /**
   * Returns a new object of class '<em>DValidator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DValidator</em>'.
   * @generated
   */
  DValidator createDValidator();

  /**
   * Returns a new object of class '<em>Component Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Description</em>'.
   * @generated
   */
  ComponentDescription createComponentDescription();

  /**
   * Returns a new object of class '<em>Ports</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ports</em>'.
   * @generated
   */
  Ports createPorts();

  /**
   * Returns a new object of class '<em>Not Allowed Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not Allowed Ref</em>'.
   * @generated
   */
  NotAllowedRef createNotAllowedRef();

  /**
   * Returns a new object of class '<em>Unit Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unit Elements</em>'.
   * @generated
   */
  UnitElements createUnitElements();

  /**
   * Returns a new object of class '<em>Component ID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component ID</em>'.
   * @generated
   */
  ComponentID createComponentID();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CDSLPackage getCDSLPackage();

} //CDSLFactory
