/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ragedev.cdsl.cDSL.ComponentDescription#getName <em>Name</em>}</li>
 *   <li>{@link de.ragedev.cdsl.cDSL.ComponentDescription#getPorts <em>Ports</em>}</li>
 *   <li>{@link de.ragedev.cdsl.cDSL.ComponentDescription#getUnits <em>Units</em>}</li>
 *   <li>{@link de.ragedev.cdsl.cDSL.ComponentDescription#getNotAllowedRef <em>Not Allowed Ref</em>}</li>
 * </ul>
 *
 * @see de.ragedev.cdsl.cDSL.CDSLPackage#getComponentDescription()
 * @model
 * @generated
 */
public interface ComponentDescription extends AbstractEntry
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getComponentDescription_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ports</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ports</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' containment reference.
   * @see #setPorts(Ports)
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getComponentDescription_Ports()
   * @model containment="true"
   * @generated
   */
  Ports getPorts();

  /**
   * Sets the value of the '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getPorts <em>Ports</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ports</em>' containment reference.
   * @see #getPorts()
   * @generated
   */
  void setPorts(Ports value);

  /**
   * Returns the value of the '<em><b>Units</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Units</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' containment reference.
   * @see #setUnits(UnitElements)
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getComponentDescription_Units()
   * @model containment="true"
   * @generated
   */
  UnitElements getUnits();

  /**
   * Sets the value of the '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getUnits <em>Units</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Units</em>' containment reference.
   * @see #getUnits()
   * @generated
   */
  void setUnits(UnitElements value);

  /**
   * Returns the value of the '<em><b>Not Allowed Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not Allowed Ref</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not Allowed Ref</em>' containment reference.
   * @see #setNotAllowedRef(NotAllowedRef)
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getComponentDescription_NotAllowedRef()
   * @model containment="true"
   * @generated
   */
  NotAllowedRef getNotAllowedRef();

  /**
   * Sets the value of the '{@link de.ragedev.cdsl.cDSL.ComponentDescription#getNotAllowedRef <em>Not Allowed Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not Allowed Ref</em>' containment reference.
   * @see #getNotAllowedRef()
   * @generated
   */
  void setNotAllowedRef(NotAllowedRef value);

} // ComponentDescription
