/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DValidator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ragedev.cdsl.cDSL.DValidator#getValName <em>Val Name</em>}</li>
 *   <li>{@link de.ragedev.cdsl.cDSL.DValidator#getRefComponents <em>Ref Components</em>}</li>
 * </ul>
 *
 * @see de.ragedev.cdsl.cDSL.CDSLPackage#getDValidator()
 * @model
 * @generated
 */
public interface DValidator extends AbstractEntry
{
  /**
   * Returns the value of the '<em><b>Val Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val Name</em>' attribute.
   * @see #setValName(String)
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getDValidator_ValName()
   * @model
   * @generated
   */
  String getValName();

  /**
   * Sets the value of the '{@link de.ragedev.cdsl.cDSL.DValidator#getValName <em>Val Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val Name</em>' attribute.
   * @see #getValName()
   * @generated
   */
  void setValName(String value);

  /**
   * Returns the value of the '<em><b>Ref Components</b></em>' reference list.
   * The list contents are of type {@link de.ragedev.cdsl.cDSL.ComponentDescription}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref Components</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Components</em>' reference list.
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getDValidator_RefComponents()
   * @model
   * @generated
   */
  EList<ComponentDescription> getRefComponents();

} // DValidator
