/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ports</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ragedev.cdsl.cDSL.Ports#getPort <em>Port</em>}</li>
 * </ul>
 *
 * @see de.ragedev.cdsl.cDSL.CDSLPackage#getPorts()
 * @model
 * @generated
 */
public interface Ports extends EObject
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute list.
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getPorts_Port()
   * @model unique="false"
   * @generated
   */
  EList<String> getPort();

} // Ports
