/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.cDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ragedev.cdsl.cDSL.UnitElements#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see de.ragedev.cdsl.cDSL.CDSLPackage#getUnitElements()
 * @model
 * @generated
 */
public interface UnitElements extends EObject
{
  /**
   * Returns the value of the '<em><b>Unit</b></em>' containment reference list.
   * The list contents are of type {@link de.ragedev.cdsl.cDSL.ComponentID}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unit</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' containment reference list.
   * @see de.ragedev.cdsl.cDSL.CDSLPackage#getUnitElements_Unit()
   * @model containment="true"
   * @generated
   */
  EList<ComponentID> getUnit();

} // UnitElements
