/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.scoping;

import de.ragedev.cdsl.scoping.AbstractCDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CDSLScopeProvider extends AbstractCDSLScopeProvider {
}
