///*
// * generated by Xtext 2.9.1
// */
//package de.ragedev.cdsl.tests
//
//import com.google.inject.Inject
//import org.eclipse.xtext.junit4.InjectWith
//import org.eclipse.xtext.junit4.XtextRunner
//import org.eclipse.xtext.junit4.util.ParseHelper
//import org.junit.Assert
//import org.junit.Test
//import org.junit.runner.RunWith
//import org.eclipse.ui.internal.Model
//
//@RunWith(XtextRunner)
//@InjectWith(CDSLInjectorProvider)
//class CDSLParsingTest{
//
//	@Inject
//	ParseHelper<Model> parseHelper;
//
//	@Test 
//	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
//	}
//
//}
