/**
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.ui;

import de.ragedev.cdsl.ui.AbstractCDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CDSLUiModule extends AbstractCDSLUiModule {
  public CDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
