/*
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.ragedev.cdsl.cDSL.CDSLPackage.eINSTANCE);
		return result;
	}
	
}
