/*
 * generated by Xtext 2.9.1
 */
package de.ragedev.cdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/ragedev/cdsl/parser/antlr/internal/InternalCDSL.tokens");
	}
}
